config/routes.rb
Rainforest::Application.routes.draw do
 

root 'products#index'
  resources :products do
    resources :reviews, :only => [:show, :create, :destroy]
  end

  resources :users, :only => [:new, :create]

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base	

		has_many :reviews
		has_many :users, through: :reviews

	def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

		validates :description, :name, :presence => true
		validates :price_in_cents, :numericality => [:only_integer => true]
		
end

app/models/review.rb
class Review < ActiveRecord::

	belongs_to :user
  belongs_to :product
  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :reviews
  has_many :products, :through => :reviews
  validates_presence_of :name
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

   before_filter :ensure_logged_in, :only => [:show]

  def index
    if params[:search]
      @products = Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      @products = Product.order('products.created_at DESC').page(params[:page])
    end
     respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(params[:id])
  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end

  def delete
  	@product = product.find(params[:id])
  	@product.destroy
  	redirect_to @product_path
  end


  private

  def product_params
  	params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController

	before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

	# before_filter :load_product


  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.review.build(review_params)
  	@review_id = current_user_id
  	if @review.save
  		redirect_to products_path, notice: 'Review created successfully'
  	else
  		render 'products/show'
  	end
  end

  def destroy

  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private

  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(paramas[:product_id])
  end

end

app/controllers/session_controller.rb
# class SessionController < ApplicationController

# 	def create
#     user = User.find_by_email(params[:email])
#   	if user && user.authenticate(params[:password])
#       session[:user_id] = user.id
#       redirect_to products_url, :notice => "Logged in!"
#    	else
#       flash.now[:alert] = "Invalid email or password"
#       render "new"
#     end
#   end
# end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
  end

  def create
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  else
  		flash.now[:alert] = "Invalid email or password"
      render "new"
  	end
 	end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out!"
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, :notice => "signed up!"
  	else
  		render "new"
  	end
  end

   private
   
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

	
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
	<p><%= product[:name] %>, <%= product[:description]%>, <%= product[:price_in_cents] %> </p>

	<%= link_to product_path(product.id) do %>
    <h2>
      <%= product.formatted_price %>
      <%= product.name %>
    </h2>
  <% end %>
  <p><%= truncate(product.description, length: 100) %></p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
	
<!--  Seach function -->

	<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>



		<!--  - - - - - - - - - - - - - - - - - - - - - - -  - -->



		 <!-- - - - - - - - - - - - - - - - - - - - - - - -  - -> -->



<h1> Products </h1>


<div>
	<%= link_to "Sign In" , new_user_path %>
</div>

<div>
	<%= link_to "Log In" , users_path %>

</div>

<div>
	<%= link_to "Create a new Product", new_product_path %>
</div>

<!-- - - - - - - - - - - - - -  - - - - - - -  - -->
<!--  -->

<%= link_to "Add a product", new_product_path %>

<!-- renders a helpful message with numbers of displayed vs. total entries -->

<hr/>

<h1>Products <small><%= page_entries_info @products %></small></h1>

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>


<!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->




	
	

app/views/products/index.js.erb
// $('#products').html("<%= j(render @products) %>");
$('#products').append('<%= j render(@products) %>');
$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<!-- <h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p> -->


<h1>New Product</p>

	<%= render form %>

	<%= link_to, "Back" product_path %>

app/views/products/show.html.erb
<% if current_user %>

  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

    <h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

<% end %>

app/views/review/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/review/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/review/show.html.erb
<h1>Review#show</h1>
<p>Find me in app/views/review/show.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>


 